CREATE TABLE XXW.PRODUCT_INFO (
	ID NUMBER(38,0) NOT NULL,
	SERIALNO VARCHAR2(18) NULL,
	TYPENO NVARCHAR2(6) NULL,
	CONSTRAINT PK_PRODUCT_INFO_ID PRIMARY KEY (ID)
);

INSERT INTO XXW.PRODUCT_INFO (ID, SERIALNO, TYPENO) VALUES(2, 's_111', '001');
INSERT INTO XXW.PRODUCT_INFO (ID, SERIALNO, TYPENO) VALUES(3, 's_222', '002');
INSERT INTO XXW.PRODUCT_INFO (ID, SERIALNO, TYPENO) VALUES(4, 's_333', '003');
INSERT INTO XXW.PRODUCT_INFO (ID, SERIALNO, TYPENO) VALUES(5, 's_444', '004');